version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=salesdb
      - DB_USER=salesuser
      - DB_PASSWORD=password123
    depends_on:
      - db
    volumes:
      - ./src/app:/app
      - /app/node_modules

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=salesdb
      - POSTGRES_USER=salesuser
      - POSTGRES_PASSWORD=password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
